### ISSUE TITLE
Next field optie bij invul velden 

### ISSUE THREAD

**Issue by RobinCrowd** [Make-some-Noise/knzb-zwemdiploma#10]
**Describe the bug**

Bij invullen zwemmer aanmaken Of account aanmaken, is het niet mogelijk om door te gaan naar next field.

**To Reproduce**
Oa kind aanmaken
Selecteer voornaam
Geen mogelijkheid om via het toetsenbord naar achternaam te gaan

**Expected behavior**
Via het toetsenbord de optie bieden om volgende veld in te vullen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 13.4

**Additional context**

**Comment by actuallymentor** [comment]
[Known issue in react native](https://github.com/facebook/react-native/issues/25721). Snoozing in expectation of a fix.

**Comment by Slapbox** [comment]
@actuallymentor, author of that issue on React-Native here. I don't think there will be any fix since it seems that behavior was never the default. Perhaps it will be adopted as a feature request instead, but wouldn't rely on anything changing on the React-Native side.
