### ISSUE TITLE
Bij het invullen van gegevens (bv. bij aanmaken diploma, aanmaken account) het veld omhoog scrollen als toetsenbord opent. 

### ISSUE THREAD

**Issue by RobinCrowd** [Make-some-Noise/knzb-zwemdiploma#12]
**Describe the bug**
Het in te vullen veld zit achter het toetsenbord waardoor deze niet zichtbaar is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by actuallymentor** [comment]
@RobinCrowd graag de details invullen die in het template staan of dingen weghalen die niet relevant zijn. Helpt heel erg bij het prio zetten voor mij :)
