### ISSUE TITLE
Opt-ins los val elkaar aan en uit kunnen zetten

### ISSUE THREAD

**Issue by RobinCrowd** [Make-some-Noise/knzb-zwemdiploma#13]
**Describe the bug**
Bij het account aanmaken zijn er 2 opt-in checkboxes. Bij het afvinken van 1, gebeurt dit ook automatisch bij checkbox 2. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by actuallymentor** [comment]
Voor nu staat hij daar als placeholder. Check even met Arjun wat daar de bedoeling voor was.
