### ISSUE TITLE
Terug en X knop werken niet (altijd) goed. Pas ruim naast het knopje werkt de functie

### ISSUE THREAD

**Issue by RobinCrowd** [Make-some-Noise/knzb-zwemdiploma#17]
**Describe the bug**
Deze functie werkt (vaak) pas bij een klik midden in de zin
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by actuallymentor** [comment]
Ik heb voor debugging specifieke schermen en stappen nodig.

**Comment by rutgervw** [comment]
Some additional info on my take on the X button

1. Open settings
2. Click the X
3. Nothing happens
4. Keep on tapping until it closes
5. Settings close after tapping multiple times

I can't figure out what's wrong, but it seems that the tappable area is ver tiny and you have to tap until you hit the right spot.

**Smartphone (please complete the following information):**
Device: iPhone 11 Pro
OS: 13.3.1

**Comment by actuallymentor** [comment]
Isolated the issue. The `onPress` was called on the `svg` which made it mandatory to press *on a part of the svg*.

I fixed it by adding a square wrapper.

Re: tabnav I made the elements grow based on space so there is no part of the tabnav that does nothing when clicked.
