### ISSUE TITLE
Zwembad locator geeft de melding: u heeft geen lokale toegang aan de app verleend

### ISSUE THREAD

**Issue by RobinCrowd** [Make-some-Noise/knzb-zwemdiploma#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by actuallymentor** [comment]
Kreeg je op enig moment een 'location access permission' popup?

**Comment by actuallymentor** [comment]
Please confirm this is still the case

**Comment by RobinCrowd** [comment]
Nee deze is gefixt
