### ISSUE TITLE
Action of X in menu - when in submenu

### ISSUE THREAD

**Issue by Armali** [Make-some-Noise/knzb-zwemdiploma#25]
**Describe the bug**
When I open the settings menu. If I tap the X in the top right corner. The menu closes. Correct behaviour.

When I open the settings menu. Go to a submenu. There is an option to go back one leve using the arrow. Here, when I click the X in the top right corner, I expect to close the whole menu. Instead it has the same functionality as the backbutton.arrow, it brings me back one level.

Android Moto G7 Power

**Comment by Armali** [comment]
@actuallymentor Yes you have fixed this. But as a result, it seems a new bug has been created. The "back functionality" of the back buttons now also close the whole menu. They should still be going back one level.

Summarizing: X should always close the whole menu. Both on top level and in deeper levels. "Back" should always go one level back, as it only appears in deeper levels of the menu.

**Comment by actuallymentor** [comment]
Thanks for the check. I found the issue and will fix it in the next pull-request.
