### ISSUE TITLE
Menu overlap - last message - message overview

### ISSUE THREAD

**Issue by Armali** [Make-some-Noise/knzb-zwemdiploma#26]
**Describe the bug**
When I use the bottom menu to go to message overview
And I scroll down to the last message
It is partly covered by the bottom nav menu

Android Moto Power G7

![image](https://user-images.githubusercontent.com/4925060/79854888-7521c000-83ca-11ea-87aa-0cfd9798a4e1.png)

**Comment by rutgervw** [comment]
This also occurs on my device

**Smartphone (please complete the following information):**
Device: iPhone 11 Pro
OS: 13.3.1
