### ISSUE TITLE
Nieuwe Zwemmer - Width of text

### ISSUE THREAD

**Issue by Armali** [Make-some-Noise/knzb-zwemdiploma#27]
**Describe the bug**
Text is wider than button.
See screenshot

Android Moto G7 power

![image](https://user-images.githubusercontent.com/4925060/79855766-af3f9180-83cb-11ea-9bd8-7985f610772d.png)

**Comment by actuallymentor** [comment]
@Armali please check if this is still the case in the latest staging version.
